import effect1 from "../images/effects/effect1.gif";
import effect2 from "../images/effects/effect2.gif";
import effect3 from "../images/effects/effect3.gif";
import effect4 from "../images/effects/effect4.gif";
import effect5 from "../images/effects/effect5.gif";
import effect6 from "../images/effects/effect6.gif";
import effect7 from "../images/effects/effect7.gif";
import effect8 from "../images/effects/effect8.gif";
import effect9 from "../images/effects/effect9.gif";
import effect10 from "../images/effects/effect10.gif";
import effect11 from "../images/effects/effect11.gif";
import effect12 from "../images/effects/effect12.gif";
import effect13 from "../images/effects/effect13.gif";
import effect14 from "../images/effects/effect14.gif";
import effect15 from "../images/effects/effect15.gif";
import effect16 from "../images/effects/effect16.gif";
import effect17 from "../images/effects/effect17.gif";
import effect18 from "../images/effects/effect18.gif";
import effect19 from "../images/effects/effect19.gif";
import effect20 from "../images/effects/effect20.gif";
import effect21 from "../images/effects/effect21.gif";
import effect22 from "../images/effects/effect22.gif";
import effect23 from "../images/effects/effect23.gif";
import effect24 from "../images/effects/effect24.gif";
import effect25 from "../images/effects/effect25.gif";
import effect26 from "../images/effects/effect26.gif";
import effect27 from "../images/effects/effect27.gif";
import effect28 from "../images/effects/effect28.gif";
import effect29 from "../images/effects/effect29.gif";
import effect30 from "../images/effects/effect30.gif";
import effect31 from "../images/effects/effect31.gif";
import effect32 from "../images/effects/effect32.gif";
import effect33 from "../images/effects/effect33.gif";
import effect34 from "../images/effects/effect34.gif";
import effect35 from "../images/effects/effect35.gif";
import effect36 from "../images/effects/effect36.gif";
import effect37 from "../images/effects/effect37.gif";
import effect38 from "../images/effects/effect38.gif";
import effect39 from "../images/effects/effect39.gif";
import effect40 from "../images/effects/effect40.gif";
import effect41 from "../images/effects/effect41.gif";
import effect42 from "../images/effects/effect42.gif";
import effect43 from "../images/effects/effect43.gif";
import effect44 from "../images/effects/effect44.gif";
import effect45 from "../images/effects/effect45.gif";
import effect46 from "../images/effects/effect46.gif";
import effect47 from "../images/effects/effect47.gif";
import effect48 from "../images/effects/effect48.gif";
import effect49 from "../images/effects/effect49.gif";
import effect58 from "../images/effects/effect58.gif";
import effect59 from "../images/effects/effect59.gif";
import effect60 from "../images/effects/effect60.gif";
import effect61 from "../images/effects/effect61.gif";
import effect62 from "../images/effects/effect62.gif";
import effect63 from "../images/effects/effect63.gif";
import effect64 from "../images/effects/effect64.gif";
import effect65 from "../images/effects/effect65.gif";
import effect66 from "../images/effects/effect66.gif";
import effect67 from "../images/effects/effect67.gif";
import effect68 from "../images/effects/effect68.gif";
import effect69 from "../images/effects/effect69.gif";

interface EffectDict {
    [key: number]: string | null;
}
const effectImages = (effectId: number): string => {
    const effectImages: EffectDict = {};

    effectImages[0] = null; // index: 0 (エフェクトなし)
    effectImages[1] = effect1;
    effectImages[2] = effect2;
    effectImages[3] = effect3;
    effectImages[4] = effect4;
    effectImages[5] = effect5;
    effectImages[6] = effect6;
    effectImages[7] = effect7;
    effectImages[8] = effect8;
    effectImages[9] = effect9;
    effectImages[10] = effect10;
    effectImages[11] = effect11;
    effectImages[12] = effect12;
    effectImages[13] = effect13;
    effectImages[14] = effect14;
    effectImages[15] = effect15;
    effectImages[16] = effect16;
    effectImages[17] = effect17;
    effectImages[18] = effect18;
    effectImages[19] = effect19;
    effectImages[20] = effect20;
    effectImages[21] = effect21;
    effectImages[22] = effect22;
    effectImages[23] = effect23;
    effectImages[24] = effect24;
    effectImages[25] = effect25;
    effectImages[26] = effect26;
    effectImages[27] = effect27;
    effectImages[28] = effect28;
    effectImages[29] = effect29;
    effectImages[30] = effect30;
    effectImages[31] = effect31;
    effectImages[32] = effect32;
    effectImages[33] = effect33;
    effectImages[34] = effect34;
    effectImages[35] = effect35;
    effectImages[36] = effect36;
    effectImages[37] = effect37;
    effectImages[38] = effect38;
    effectImages[39] = effect39;
    effectImages[40] = effect40;
    effectImages[41] = effect41;
    effectImages[42] = effect42;
    effectImages[43] = effect43;
    effectImages[44] = effect44;
    effectImages[45] = effect45;
    effectImages[46] = effect46;
    effectImages[47] = effect47;
    effectImages[48] = effect48;
    effectImages[49] = effect49;
    effectImages[50] = null;
    effectImages[51] = null;
    effectImages[52] = null;
    effectImages[53] = null;
    effectImages[54] = null;
    effectImages[55] = null;
    effectImages[56] = null;
    effectImages[57] = null;
    effectImages[58] = effect58;
    effectImages[59] = effect59;
    effectImages[60] = effect60;
    effectImages[61] = effect61;
    effectImages[62] = effect62;
    effectImages[63] = effect63;
    effectImages[64] = effect64;
    effectImages[65] = effect65;
    effectImages[66] = effect66;
    effectImages[67] = effect67;
    effectImages[68] = effect68;
    effectImages[69] = effect69;

    return effectImages[effectId] ?? "";
}

export default effectImages;