import killerBee1 from "../images/monsters/killerBee1.png";
import killerBee2 from "../images/monsters/killerBee2.png";
import killerBee3 from "../images/monsters/killerBee3.png";
import carmilla1 from "../images/monsters/carmilla1.png";
import carmilla2 from "../images/monsters/carmilla2.png";
import daemon1 from "../images/monsters/daemon1.png";
import daemon2 from "../images/monsters/daemon2.png";
import goblin1 from "../images/monsters/goblin1.png"
import goblin2 from "../images/monsters/goblin2.png"
import goblin3 from "../images/monsters/goblin3.png"
import golem1 from "../images/monsters/golem1.png";
import golem2 from "../images/monsters/golem2.png";
import golem3 from "../images/monsters/golem3.png";
import harpy1 from "../images/monsters/harpy1.png";
import harpy2 from "../images/monsters/harpy2.png";
import knight1 from "../images/monsters/knight1.png";
import knight2 from "../images/monsters/knight2.png";
import knight3 from "../images/monsters/knight3.png";
import magician1 from "../images/monsters/magician1.png";
import magician2 from "../images/monsters/magician2.png";
import magician3 from "../images/monsters/magician3.png";
import matango1 from "../images/monsters/matango1.png";
import matango2 from "../images/monsters/matango2.png";
import needleBird1 from "../images/monsters/needleBird1.png";
import needleBird2 from "../images/monsters/needleBird2.png";
import petitDragon1 from "../images/monsters/petitDragon1.png";
import petitDragon2 from "../images/monsters/petitDragon2.png";
import petitDragon3 from "../images/monsters/petitDragon3.png";
import petitDragon4 from "../images/monsters/petitDragon4.png";
import poto1 from "../images/monsters/poto1.png";
import poto2 from "../images/monsters/poto2.png";
import poto3 from "../images/monsters/poto3.png";
import priest1 from "../images/monsters/priest1.png";
import priest2 from "../images/monsters/priest2.png";
import priest3 from "../images/monsters/priest3.png";
import rabi1 from "../images/monsters/rabi1.png";
import rabi2 from "../images/monsters/rabi2.png";
import rabi3 from "../images/monsters/rabi3.png";
import rabi4 from "../images/monsters/rabi4.png";
import slime1 from "../images/monsters/slime1.png";
import slime2 from "../images/monsters/slime2.png";
import slime3 from "../images/monsters/slime3.png";
import sword1 from "../images/monsters/sword1.png";
import sword2 from "../images/monsters/sword2.png";
import sword3 from "../images/monsters/sword3.png";
import wolf1 from "../images/monsters/wolf1.png";
import wolf2 from "../images/monsters/wolf2.png";
import wolf3 from "../images/monsters/wolf3.png";
import duck1 from "../images/monsters/duck1.png";
import duck2 from "../images/monsters/duck2.png";
import mallBear1 from "../images/monsters/mallBear1.png";
import mallBear2 from "../images/monsters/mallBear2.png";
import galBee1 from "../images/monsters/galBee1.png";
import galBee2 from "../images/monsters/galBee2.png";
import galBee3 from "../images/monsters/galBee3.png";
import fisheman1 from "../images/monsters/fisheman1.png";
import fisheman2 from "../images/monsters/fisheman2.png";
import caterpillar1 from "../images/monsters/caterpillar1.png";
import caterpillar2 from "../images/monsters/caterpillar2.png";
import caterpillar3 from "../images/monsters/caterpillar3.png";
import packn1 from "../images/monsters/packn1.png";
import packn2 from "../images/monsters/packn2.png";
import packn3 from "../images/monsters/packn3.png";
import packn4 from "../images/monsters/packn4.png";
import miniDevil1 from "../images/monsters/miniDevil1.png";
import miniDevil2 from "../images/monsters/miniDevil2.png";
import ogreBox1 from "../images/monsters/ogreBox1.png";
import ogreBox2 from "../images/monsters/ogreBox2.png";
import vallette1 from "../images/monsters/vallette1.png";
import vallette2 from "../images/monsters/vallette2.png";
import basilisk1 from "../images/monsters/basilisk1.png";
import basilisk2 from "../images/monsters/basilisk2.png";
import specter1 from "../images/monsters/specter1.png";
import specter2 from "../images/monsters/specter2.png";
import unicornHead1 from "../images/monsters/unicornHead1.png";
import unicornHead2 from "../images/monsters/unicornHead2.png";
import shadow1 from "../images/monsters/shadow1.png";
import shadow2 from "../images/monsters/shadow2.png";
import shadow3 from "../images/monsters/shadow3.png";
import boulder1 from "../images/monsters/boulder1.png";
import boulder2 from "../images/monsters/boulder2.png";
import boulder3 from "../images/monsters/boulder3.png";
import pumpkin1 from "../images/monsters/pumpkin1.png";
import pumpkin2 from "../images/monsters/pumpkin2.png";

interface MonsterDict {
    [key: number]: string | undefined;
}

const monsterImages = (monsterId: number) => {
    const monsterImages: MonsterDict = {};

    monsterImages[0] = ""; // index: 0 (モンスター無し)
    monsterImages[1] = killerBee1;
    monsterImages[2] = killerBee2;
    monsterImages[3] = killerBee3;
    monsterImages[4] = carmilla1;
    monsterImages[5] = carmilla2;
    monsterImages[6] = daemon1;
    monsterImages[7] = daemon2;
    monsterImages[8] = goblin1;
    monsterImages[9] = goblin2;
    monsterImages[10] = goblin3;
    monsterImages[11] = golem1;
    monsterImages[12] = golem2;
    monsterImages[13] = golem3;
    monsterImages[14] = harpy1;
    monsterImages[15] = harpy2;
    monsterImages[16] = knight1;
    monsterImages[17] = knight2;
    monsterImages[18] = knight3;
    monsterImages[19] = magician1;
    monsterImages[20] = magician2;
    monsterImages[21] = magician3;
    monsterImages[22] = matango1;
    monsterImages[23] = matango2;
    monsterImages[24] = needleBird1;
    monsterImages[25] = needleBird2;
    monsterImages[26] = petitDragon1;
    monsterImages[27] = petitDragon2;
    monsterImages[28] = petitDragon3;
    monsterImages[29] = petitDragon4;
    monsterImages[30] = poto1;
    monsterImages[31] = poto2;
    monsterImages[32] = poto3;
    monsterImages[33] = priest1;
    monsterImages[34] = priest2;
    monsterImages[35] = priest3;
    monsterImages[36] = rabi1;
    monsterImages[37] = rabi2;
    monsterImages[38] = rabi3;
    monsterImages[39] = rabi4;
    monsterImages[40] = slime1;
    monsterImages[41] = slime2;
    monsterImages[42] = slime3;
    monsterImages[43] = sword1;
    monsterImages[44] = sword2;
    monsterImages[45] = sword3;
    monsterImages[46] = wolf1;
    monsterImages[47] = wolf2;
    monsterImages[48] = wolf3;
    monsterImages[49] = duck1;
    monsterImages[50] = duck2;
    monsterImages[51] = mallBear1;
    monsterImages[52] = mallBear2;
    monsterImages[53] = galBee1;
    monsterImages[54] = galBee2;
    monsterImages[55] = galBee3;
    monsterImages[56] = fisheman1;
    monsterImages[57] = fisheman2;
    monsterImages[58] = caterpillar1;
    monsterImages[59] = caterpillar2;
    monsterImages[60] = caterpillar3;
    monsterImages[61] = packn1;
    monsterImages[62] = packn2;
    monsterImages[63] = packn3;
    monsterImages[64] = packn4;
    monsterImages[65] = miniDevil1;
    monsterImages[66] = miniDevil2;
    monsterImages[67] = ogreBox1;
    monsterImages[68] = ogreBox2;
    monsterImages[69] = vallette1;
    monsterImages[70] = vallette2;
    monsterImages[71] = basilisk1;
    monsterImages[72] = basilisk2;
    monsterImages[73] = specter1;
    monsterImages[74] = specter2;
    monsterImages[75] = unicornHead1;
    monsterImages[76] = unicornHead2;
    monsterImages[77] = shadow1;
    monsterImages[78] = shadow2;
    monsterImages[79] = shadow3;
    monsterImages[80] = boulder1;
    monsterImages[81] = boulder2;
    monsterImages[82] = boulder3;
    monsterImages[83] = pumpkin1;
    monsterImages[84] = pumpkin2;

    return monsterImages[monsterId];
}

export default monsterImages;