import killerBee1 from "../images/monsters/killerBee1.png";
import killerBee2 from "../images/monsters/killerBee2.png";
import killerBee3 from "../images/monsters/killerBee3.png";
import carmilla1 from "../images/monsters/carmilla1.png";
import carmilla2 from "../images/monsters/carmilla2.png";
import daemon1 from "../images/monsters/daemon1.png";
import daemon2 from "../images/monsters/daemon2.png";
import goblin1 from "../images/monsters/goblin1.png"
import goblin2 from "../images/monsters/goblin2.png"
import goblin3 from "../images/monsters/goblin3.png"
import golem1 from "../images/monsters/golem1.png";
import golem2 from "../images/monsters/golem2.png";
import golem3 from "../images/monsters/golem3.png";
import harpy1 from "../images/monsters/harpy1.png";
import harpy2 from "../images/monsters/harpy2.png";
import knight1 from "../images/monsters/knight1.png";
import knight2 from "../images/monsters/knight2.png";
import knight3 from "../images/monsters/knight3.png";
import magician1 from "../images/monsters/magician1.png";
import magician2 from "../images/monsters/magician2.png";
import magician3 from "../images/monsters/magician3.png";
import matango1 from "../images/monsters/matango1.png";
import matango2 from "../images/monsters/matango2.png";
import needleBird1 from "../images/monsters/needleBird1.png";
import needleBird2 from "../images/monsters/needleBird2.png";
import petitDragon1 from "../images/monsters/petitDragon1.png";
import petitDragon2 from "../images/monsters/petitDragon2.png";
import petitDragon3 from "../images/monsters/petitDragon3.png";
import petitDragon4 from "../images/monsters/petitDragon4.png";
import poto1 from "../images/monsters/poto1.png";
import poto2 from "../images/monsters/poto2.png";
import poto3 from "../images/monsters/poto3.png";
import priest1 from "../images/monsters/priest1.png";
import priest2 from "../images/monsters/priest2.png";
import priest3 from "../images/monsters/priest3.png";
import rabi1 from "../images/monsters/rabi1.png";
import rabi2 from "../images/monsters/rabi2.png";
import rabi3 from "../images/monsters/rabi3.png";
import rabi4 from "../images/monsters/rabi4.png";
import slime1 from "../images/monsters/slime1.png";
import slime2 from "../images/monsters/slime2.png";
import slime3 from "../images/monsters/slime3.png";
import sword1 from "../images/monsters/sword1.png";
import sword2 from "../images/monsters/sword2.png";
import sword3 from "../images/monsters/sword3.png";
import wolf1 from "../images/monsters/wolf1.png";
import wolf2 from "../images/monsters/wolf2.png";
import wolf3 from "../images/monsters/wolf3.png";
import duck1 from "../images/monsters/duck1.png";
import duck2 from "../images/monsters/duck2.png";
import mallBear1 from "../images/monsters/mallBear1.png";
import mallBear2 from "../images/monsters/mallBear2.png";
import galBee1 from "../images/monsters/galBee1.png";
import galBee2 from "../images/monsters/galBee2.png";
import galBee3 from "../images/monsters/galBee3.png";
import fisheman1 from "../images/monsters/fisheman1.png";
import fisheman2 from "../images/monsters/fisheman2.png";
import caterpillar1 from "../images/monsters/caterpillar1.png";
import caterpillar2 from "../images/monsters/caterpillar2.png";
import caterpillar3 from "../images/monsters/caterpillar3.png";
import packn1 from "../images/monsters/packn1.png";
import packn2 from "../images/monsters/packn2.png";
import packn3 from "../images/monsters/packn3.png";
import packn4 from "../images/monsters/packn4.png";
import miniDevil1 from "../images/monsters/miniDevil1.png";
import miniDevil2 from "../images/monsters/miniDevil2.png";
import ogreBox1 from "../images/monsters/ogreBox1.png";
import ogreBox2 from "../images/monsters/ogreBox2.png";
import vallette1 from "../images/monsters/vallette1.png";
import vallette2 from "../images/monsters/vallette2.png";
import basilisk1 from "../images/monsters/basilisk1.png";
import basilisk2 from "../images/monsters/basilisk2.png";
import specter1 from "../images/monsters/specter1.png";
import specter2 from "../images/monsters/specter2.png";
import unicornHead1 from "../images/monsters/unicornHead1.png";
import unicornHead2 from "../images/monsters/unicornHead2.png";
import shadow1 from "../images/monsters/shadow1.png";
import shadow2 from "../images/monsters/shadow2.png";
import shadow3 from "../images/monsters/shadow3.png";
import boulder1 from "../images/monsters/boulder1.png";
import boulder2 from "../images/monsters/boulder2.png";
import boulder3 from "../images/monsters/boulder3.png";
import pumpkin1 from "../images/monsters/pumpkin1.png";
import pumpkin2 from "../images/monsters/pumpkin2.png";

const monsterImages = (monsterId: number) => {
    const monsterImages = [];

    monsterImages.push(""); // index: 0 (モンスター無し)
    monsterImages.push(killerBee1);
    monsterImages.push(killerBee2);
    monsterImages.push(killerBee3);
    monsterImages.push(carmilla1);
    monsterImages.push(carmilla2);
    monsterImages.push(daemon1);
    monsterImages.push(daemon2);
    monsterImages.push(goblin1);
    monsterImages.push(goblin2);
    monsterImages.push(goblin3);
    monsterImages.push(golem1);
    monsterImages.push(golem2);
    monsterImages.push(golem3);
    monsterImages.push(harpy1);
    monsterImages.push(harpy2);
    monsterImages.push(knight1);
    monsterImages.push(knight2);
    monsterImages.push(knight3);
    monsterImages.push(magician1);
    monsterImages.push(magician2);
    monsterImages.push(magician3);
    monsterImages.push(matango1);
    monsterImages.push(matango2);
    monsterImages.push(needleBird1);
    monsterImages.push(needleBird2);
    monsterImages.push(petitDragon1);
    monsterImages.push(petitDragon2);
    monsterImages.push(petitDragon3);
    monsterImages.push(petitDragon4);
    monsterImages.push(poto1);
    monsterImages.push(poto2);
    monsterImages.push(poto3);
    monsterImages.push(priest1);
    monsterImages.push(priest2);
    monsterImages.push(priest3);
    monsterImages.push(rabi1);
    monsterImages.push(rabi2);
    monsterImages.push(rabi3);
    monsterImages.push(rabi4);
    monsterImages.push(slime1);
    monsterImages.push(slime2);
    monsterImages.push(slime3);
    monsterImages.push(sword1);
    monsterImages.push(sword2);
    monsterImages.push(sword3);
    monsterImages.push(wolf1);
    monsterImages.push(wolf2);
    monsterImages.push(wolf3);
    monsterImages.push(duck1);
    monsterImages.push(duck2);
    monsterImages.push(mallBear1);
    monsterImages.push(mallBear2);
    monsterImages.push(galBee1);
    monsterImages.push(galBee2);
    monsterImages.push(galBee3);
    monsterImages.push(fisheman1);
    monsterImages.push(fisheman2);
    monsterImages.push(caterpillar1);
    monsterImages.push(caterpillar2);
    monsterImages.push(caterpillar3);
    monsterImages.push(packn1);
    monsterImages.push(packn2);
    monsterImages.push(packn3);
    monsterImages.push(packn4);
    monsterImages.push(miniDevil1);
    monsterImages.push(miniDevil2);
    monsterImages.push(ogreBox1);
    monsterImages.push(ogreBox2);
    monsterImages.push(vallette1);
    monsterImages.push(vallette2);
    monsterImages.push(basilisk1);
    monsterImages.push(basilisk2);
    monsterImages.push(specter1);
    monsterImages.push(specter2);
    monsterImages.push(unicornHead1);
    monsterImages.push(unicornHead2);
    monsterImages.push(shadow1);
    monsterImages.push(shadow2);
    monsterImages.push(shadow3);
    monsterImages.push(boulder1);
    monsterImages.push(boulder2);
    monsterImages.push(boulder3);
    monsterImages.push(pumpkin1);
    monsterImages.push(pumpkin2);

    // outOfMemory ガード（画像表示なし）
    if (monsterId >= monsterImages.length) monsterId = 0;

    return monsterImages[monsterId];
}

export default monsterImages;